coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 0.5%
    patch:
      default:
        target: 50%
        threshold: 0.5%
codecov:
  token: a9e66ea7-a5dd-4493-9f88-f68ed898a536
