web-compile:
  sass:
    files:
      src/scss/quantumghent-book-theme.scss: quantumghent_book_theme/static/quantumghent-book-theme.[hash].css
    precision: 5
    sourcemap: false
    format: compressed
  js:
    files:
      src/js/quantumghent-book-theme.js: quantumghent_book_theme/static/quantumghent-book-theme.[hash].js
  jinja:
    files:
      src/jinja/theme.conf.j2: quantumghent_book_theme/theme.conf
